apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infra
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./apps/envs/uat/westeurope"
  prune: true
  timeout: 5m0s
