# Example: How to use registry credentials in your applications
# This shows how podinfo would reference private registry images

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  values:
    # Use image from private ACR
    image:
      repository: yourregistry.azurecr.io/podinfo
      tag: "6.6.0"

    # Reference the registry credentials
    imagePullSecrets:
      - name: acr-credentials

    # Use the workload identity service account
    serviceAccount:
      create: false # Use existing service account
      name: workload-identity-sa

    # Pod security context (recommended)
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
