apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workload-identity.yaml
  - registry-config.yaml
  - external-secrets.yaml        # Azure Key Vault integration
  # Alternative approaches (comment out if using Key Vault):
  # - image-pull-secrets.yaml    # For manual secret management
