apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
  labels:
    region: eastasia
    environment: prod
spec:
  chart:
    spec:
      version: "61.9.x"
  values:
    commonLabels:
      environment: prod
      region: eastasia
      topology.kubernetes.io/region: eastasia
    # Regional hostnames
    grafana:
      ingress:
        hosts:
          - "grafana-eastasia-prod.example.com"
        tls:
          - hosts:
              - "grafana-eastasia-prod.example.com"
      nodeSelector:
        topology.kubernetes.io/region: eastasia
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"

    prometheus:
      ingress:
        hosts:
          - "prometheus-eastasia-prod.example.com"
        tls:
          - hosts:
              - "prometheus-eastasia-prod.example.com"
      prometheusSpec:
        nodeSelector:
          topology.kubernetes.io/region: eastasia
        resources:
          requests:
            cpu: "200m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        retention: "30d"
        retentionSize: "50GB"

    alertmanager:
      ingress:
        hosts:
          - "alertmanager-eastasia-prod.example.com"
        tls:
          - hosts:
              - "alertmanager-eastasia-prod.example.com"
      alertmanagerSpec:
        nodeSelector:
          topology.kubernetes.io/region: eastasia
