apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/kurrentdb-operator/

# Strategic merge patch for regional configuration
patchesStrategicMerge:
- kurrentdb-operator-patch.yaml
