apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
  labels:
    region: westeurope
    environment: dev
spec:
  chart:
    spec:
      version: 1.18.0
  values:
    startupapicheck:
      enabled: false
