apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
  labels:
    region: westeurope
    environment: dev
spec:
  # For Dev environment. The service is type: loadbalancer. In KIND cluster it will not receive an IP address and Flux won't get healthy.
  install:
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      version: 4.12.3
  values:
    controller:
      replicaCount: 1
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-resource-group: "rg-westeurope-dev"
