apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kurrentdb-operator
  namespace: flux-system
  labels:
    environment: dev
    region: westeurope
spec:
  chart:
    spec:
      version: 1.1.0
  values:
    operator:
      # resources:
      #   requests:
      #     memory: 64Mi
      #     cpu: 1000m
      #   limits:
      #     memory: 128Mi
      logging:
        level: info
      # license:
      #   secretName: operator-license
