apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cert-manager/
  # - ../../../base/ingress-nginx/
  - ../../../base/kube-prometheus-stack/
  # - ../../../base/kurrentdb-operator/
  # - ../../../base/kurrentdb-monitoring/
  - ../../../base/contour/

labels:
  - includeSelectors: true
    pairs:
      environment: dev
      region: westeurope
      topology.kubernetes.io/region: westeurope
patches:
  - path: cert-manager-patch.yaml
  # - path: ingress-nginx-patch.yaml
  - path: kube-prometheus-stack-patch.yaml
  # - path: kurrentdb-operator-patch.yaml
  - path: contour-patch.yaml
