apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: contour
  namespace: flux-system
spec:
  releaseName: contour
  interval: 30m
  chart:
    spec:
      chart: contour
      version: 21.0.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  targetNamespace: contour
  values:
