apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kurrentdb-operator
  namespace: flux-system
spec:
  interval: 24h
  url: https://packages.kurrent.io/basic/kurrent-latest/helm/charts/
