# Production environment - Restricted RBAC for developers (East Asia)
# Developers have read-only access in production

---
# Developers get read-only access in production (East Asia)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-ad-developers-prod-readonly-eastasia
  labels:
    region: "eastasia"
    environment: "prod"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-ad-viewer
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "DEVELOPER_GROUP_EASTASIA_ID" # Replace with Azure AD group object ID for East Asia

---
# Remove default developer permissions in production (East Asia)
# (This effectively overrides the base developer permissions)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-ad-developers-eastasia
  labels:
    region: "eastasia"
    environment: "prod"
subjects: [] # Empty subjects removes the binding
