apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: default
  labels:
    region: "eastasia"
    environment: "prod"
spec:
  hard:
    requests.cpu: "8" # Higher limits for prod
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "50" # More capacity for prod
