apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/kurrentdb-primary/

# Strategic merge patch for production configuration
patchesStrategicMerge:
- kurrentdb-cluster-patch.yaml
