apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# KurrentDB monitoring base configuration
# This provides the base ServiceMonitors, PrometheusRules, and Grafana dashboards

resources:
- servicemonitor.yaml
- prometheusrule.yaml
- grafana-dashboards.yaml

commonLabels:
  app.kubernetes.io/name: kurrentdb-monitoring
  app.kubernetes.io/component: monitoring
