apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager
  - external-secrets
  # - ingress-nginx
  # - kube-prometheus-stack
  - kurrentdb-monitoring
  - kurrentdb-operator
  - contour

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: flux
      app.kubernetes.io/part-of: platform-infrastructure
