apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kurrentdb-operator
  labels:
    environment: prod
    region: westeurope
spec:
  values:
    commonLabels:
      environment: prod
      region: westeurope
      topology.kubernetes.io/region: westeurope
    logLevel: "debug"
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    leaderElection:
      retryPeriod: "1s"
    metrics:
      serviceMonitor:
        interval: "15s"
    nodeSelector:
      topology.kubernetes.io/region: westeurope
