apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/
patchesStrategicMerge:
  - resource-limits-prod-patch.yaml
  - registry-config-patch.yaml
  - keyvault-store-patch.yaml
  - kubectl-rbac-prod-patch.yaml
