# Development environment Key Vault configuration for East Asia
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: default
spec:
  provider:
    azurekv:
      # Development Key Vault in East Asia region
      vaultUrl: "https://keyvault-eastasia-dev.vault.azure.net/"
      authType: WorkloadIdentity
      serviceAccountRef:
        name: workload-identity-sa
