apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
  labels:
    region: eastasia
    environment: uat
spec:
  chart:
    spec:
      version: "58.x"
  values:
    commonLabels:
      environment: uat
      region: eastasia
      topology.kubernetes.io/region: eastasia
    # Regional hostnames
    grafana:
      ingress:
        hosts:
          - "grafana-eastasia-uat.example.com"
        tls:
          - hosts:
              - "grafana-eastasia-uat.example.com"
      nodeSelector:
        topology.kubernetes.io/region: eastasia
      resources:
        requests:
          cpu: "75m"
          memory: "192Mi"
        limits:
          cpu: "300m"
          memory: "384Mi"

    prometheus:
      ingress:
        hosts:
          - "prometheus-eastasia-uat.example.com"
        tls:
          - hosts:
              - "prometheus-eastasia-uat.example.com"
      prometheusSpec:
        nodeSelector:
          topology.kubernetes.io/region: eastasia
        resources:
          requests:
            cpu: "150m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        retention: "14d"
        retentionSize: "20GB"

    alertmanager:
      ingress:
        hosts:
          - "alertmanager-eastasia-uat.example.com"
        tls:
          - hosts:
              - "alertmanager-eastasia-uat.example.com"
      alertmanagerSpec:
        nodeSelector:
          topology.kubernetes.io/region: eastasia
