apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
  labels:
    region: eastasia
    environment: prod
spec:
  chart:
    spec:
      version: "v1.13.x"
  values:
    replicaCount: 3
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    nodeSelector:
      topology.kubernetes.io/region: eastasia
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: cert-manager
              topologyKey: kubernetes.io/hostname
