apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
  labels:
    region: eastasia
    environment: prod
spec:
  chart:
    spec:
      version: "4.8.x"
  values:
    controller:
      replicaCount: 3
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
      nodeSelector:
        topology.kubernetes.io/region: eastasia
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-resource-group: "rg-eastasia-prod"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: ingress-nginx
              topologyKey: kubernetes.io/hostname
