apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/cert-manager/
- ../../../base/external-secrets/
- ../../../base/ingress-nginx/
- ../../../base/kube-prometheus-stack/
- ../../../base/kurrentdb-monitoring/

# Add environment and region labels

# Strategic merge patches for regional configuration
labels:
- includeSelectors: true
  pairs:
    environment: prod
    region: eastasia
    topology.kubernetes.io/region: eastasia
patches:
- path: cert-manager-patch.yaml
- path: external-secrets-patch.yaml
- path: ingress-nginx-patch.yaml
- path: kube-prometheus-stack-patch.yaml
- path: kurrentdb-monitoring-patch.yaml
