apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/podinfo/

patches:
  - target:
      kind: HelmRelease
      name: podinfo
    patch: |-
      - op: replace
        path: /spec/values/replicaCount
        value: 2
      - op: add
        path: /metadata/labels/environment
        value: "uat"
      - op: add
        path: /metadata/labels/region
        value: "westeurope"
      - op: replace
        path: /spec/values/image/tag
        value: "6.0.1"
      - op: replace
        path: /spec/values/resources/requests/cpu
        value: "50m"
      - op: replace
        path: /spec/values/resources/requests/memory
        value: "64Mi"
      - op: replace
        path: /spec/values/resources/limits/cpu
        value: "200m"
      - op: replace
        path: /spec/values/resources/limits/memory
        value: "128Mi"
      - op: add
        path: /spec/values/nodeSelector
        value:
          topology.kubernetes.io/region: westeurope
      - op: add
        path: /spec/values/podAnnotations/region
        value: "westeurope"
      - op: add
        path: /spec/values/podAnnotations/environment
        value: "uat"
      - op: add
        path: /spec/values/affinity
        value:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: podinfo
                topologyKey: kubernetes.io/hostname
