apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./infra-configs/envs/dev/westeurope"
  prune: true
  wait: true
  timeout: 5m0s
