apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/kurrentdb-primary/

# Strategic merge patch for regional configuration
patches:
- path: kurrentdb-cluster-patch.yaml
