apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/
patchesStrategicMerge:
  - rbac-dev-patch.yaml
  - resource-limits-dev-patch.yaml
  - registry-config-patch.yaml
  - keyvault-store-patch.yaml
  - kubectl-rbac-dev-patch.yaml
