apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: default
data:
  # Development - more relaxed settings
  acr-registry: "yourregistry.azurecr.io"
  acr-enabled: "true"
  
  # Allow Docker Hub for development
  dockerhub-enabled: "true"
  
  # Allow private registries for testing
  private-registry-enabled: "true"
  
  # Use latest images in dev
  image-pull-policy: "Always"
  
  # Development-specific settings
  allow-insecure-registries: "true"
  skip-tls-verify: "true"
