apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager
  - external-secrets
  # - kurrentdb-monitoring

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/managed-by: flux
      app.kubernetes.io/part-of: platform-infrastructure
