apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
  labels:
    region: eastasia
    environment: dev
spec:
  chart:
    spec:
      version: "4.8.x"
  values:
    controller:
      replicaCount: 1
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
      nodeSelector:
        topology.kubernetes.io/region: eastasia
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-resource-group: "rg-eastasia-dev"
