apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  releaseName: ingress-nginx
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  targetNamespace: ingress-nginx
  values:
    controller:
      replicaCount: 1
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: monitoring
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
      resources:
        limits:
          cpu: 100m
          memory: 90Mi
        requests:
          cpu: 100m
          memory: 90Mi
